# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09b3a8a409822199e0b58c8762dda7d3a23b2036e0fb5db14772e387353d7797cc72c097b6f7728e7a0604bf69c26bd667f853adbe773714ce5bf8d0481af54d

test:
  secret_key_base: a2f28019cbb83377dac5134c858fe62d7a43fd1da22eda1f74b1d63f4502c06b4276ba6cb5f5d37df94cb2783b7fa1c4640a3bb22d9b7fc33e571a7a38d105ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
